#PBS -N running_again
#PBS -l nodes=2:ppn=4
#PBS -l pmem=2gb
#PBS -l walltime=00:15:00
#PBS -q coc-ice
#PBS -j oe
#PBS -o myjob.out
#PBS -m abe
#PBS -M anagarajan8@gatech.edu
cd ~/APT/se2
module load gcc/4.9.0
module load cmake/3.9.1
module load openmpi

echo "** Starting Test **"
for (( j=1; j<=12; j++))
do
	echo "Starting for $j processes"
	/usr/lib64/openmpi/bin/mpirun --hostfile $PBS_NODEFILE -np $j ./heat1D 10.5 20.2 11 20
	echo "Ended $j processes"
done

